Restored accidental modification in: builds/Resources/Include_bluesim.mk (discussion follows)
In the definition of BSC_C_FLAGS, the following:

    -Xc++  -D_GLIBCXX_USE_CXX11_ABI=0

is problematic.  Whether it's needed or not depends on version
differences between the gcc used to build bsc libraries (that come
with your pre-built installed bsc distribution) vs. your local gcc
invoked by bsc on your user code; they need to agree on CX11_ABI (gcc
changed its ABI not long ago).

If mismatched, when you run your Bluesim executable, you get
dynamic-load error messages like this:

    $ ./exe_HW_sim
    Error: dlopen: ./exe_HW_sim.so: undefined symbol: _Z27dollar_test_dollar_plusargsP9tSimStatePKcPKSs
        invoked from within
    "sim load $model_name $top_module"
        invoked from within
    "if {$wait} {
    sim load $model_name $top_module wait
    } else {
    sim load $model_name $top_module
    }"
        (file "/home/nikhil/NoBak/Bluespec-2019.05.beta2-debian9stretch-amd64/lib/tcllib/bluespec/bluesim.tcl" line 176)